// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
	models "github.com/yy-at-here/psql_update/bobmodels/models"
)

type Factory struct {
	baseBenchmarkAccountMods BenchmarkAccountModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewBenchmarkAccount(mods ...BenchmarkAccountMod) *BenchmarkAccountTemplate {
	return f.NewBenchmarkAccountWithContext(context.Background(), mods...)
}

func (f *Factory) NewBenchmarkAccountWithContext(ctx context.Context, mods ...BenchmarkAccountMod) *BenchmarkAccountTemplate {
	o := &BenchmarkAccountTemplate{f: f}

	if f != nil {
		f.baseBenchmarkAccountMods.Apply(ctx, o)
	}

	BenchmarkAccountModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingBenchmarkAccount(m *models.BenchmarkAccount) *BenchmarkAccountTemplate {
	o := &BenchmarkAccountTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.Status = func() string { return m.Status }
	o.Balance = func() decimal.Decimal { return m.Balance }
	o.LastAccessed = func() time.Time { return m.LastAccessed }
	o.Version = func() int32 { return m.Version }
	o.Note = func() string { return m.Note }

	return o
}

func (f *Factory) ClearBaseBenchmarkAccountMods() {
	f.baseBenchmarkAccountMods = nil
}

func (f *Factory) AddBaseBenchmarkAccountMod(mods ...BenchmarkAccountMod) {
	f.baseBenchmarkAccountMods = append(f.baseBenchmarkAccountMods, mods...)
}
